// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnpqdalcTjMzRvhWGgs6lo4HUqG4OFFtE',
    appId: '1:844751963419:web:ab42458e504539c2787fbe',
    messagingSenderId: '844751963419',
    projectId: 'ttracker-17cae',
    authDomain: 'ttracker-17cae.firebaseapp.com',
    storageBucket: 'ttracker-17cae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMd52rTsbPpH1d6kThMhj6mXlv5nrcPKc',
    appId: '1:844751963419:android:196d173e6e28f3c7787fbe',
    messagingSenderId: '844751963419',
    projectId: 'ttracker-17cae',
    storageBucket: 'ttracker-17cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2OBcvX-vItTKfIraQc7NKKunor24qZoI',
    appId: '1:844751963419:ios:3d9061c2d9c3bbbc787fbe',
    messagingSenderId: '844751963419',
    projectId: 'ttracker-17cae',
    storageBucket: 'ttracker-17cae.appspot.com',
    iosClientId: '844751963419-nk9e12nvl8mguav1lj3pam31g1i1fqao.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTableTrackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2OBcvX-vItTKfIraQc7NKKunor24qZoI',
    appId: '1:844751963419:ios:dee0e307a588dc48787fbe',
    messagingSenderId: '844751963419',
    projectId: 'ttracker-17cae',
    storageBucket: 'ttracker-17cae.appspot.com',
    iosClientId: '844751963419-dch7vleebe08afs14c76ci8p0dsoaunj.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTableTrackerFlutter.RunnerTests',
  );
}
